### ISSUE TITLE
How can you be so awesome?

### ISSUE THREAD

**Issue by satya164** [kenwheeler/ama#1]

**Comment by kenwheeler** [comment]
I come from a long line of awesome, and its my duty to carey the torch. I chalk it up to not giving a fuck as a baseline rule. Not to say I dont take responsibilities seriously, but that I do essentially what I want and dont fear reprecussions, within a reasonable scope.

**Comment by kenwheeler** [comment]
Carry*

**Comment by k15a** [comment]
Someone should create a ken wheeler awesome list ;)
