### ISSUE TITLE
Can you spec your Jeep?

### ISSUE THREAD

**Issue by grabbou** [kenwheeler/ama#12]
Was thinking about a new car

**Comment by kenwheeler** [comment]
Its a 2015 Wrangler Unlimited Sport. 

- 35" AT Tires
- Pro Comp Rock Crawler Rims with security bolt lug nuts
- A 50" 10000 lumen light bar
- Black steel grid pattern cowl armor
- Black grid taillight covers
- A HiLift farm jack, mounted to the rear.
- Offroad antenna
- 2" Wheel spacers to push the wheel base wider.
- 2" suspension lift
- Hydraulic jack and cross style lug wrench in the cutaway
- Speaker upgrade
- Little pieces of cheerios and lollipops and other childrens food, just stomped into the rug and under the seats and in between the cushions.

In the future, I'd like to:

- Remove the doors and put on cargo net tube doors: https://www.amazon.com/Body-Armor-4x4-JK-6139-Black/dp/B00S15PMK4
- Rear cargo net: https://www.amazon.com/Smittybilt-581035-Diamond-Restraint-System/dp/B003EOZIP6/ref=sr_1_1?s=automotive&ie=UTF8&qid=1493137147&sr=1-1&keywords=cargo+net+jeep
- A mean ass stubby bumper: https://www.amazon.com/GSI-Wrangler-Textured-Stubby-Bumper/dp/B01EZTVOQA/ref=sr_1_1?ie=UTF8&qid=1493137218&sr=8-1-spons&keywords=jeep+bumper&psc=1
- Throw a sub in the back
- Make an LED plate for the back window where I can send messages with RN
