### ISSUE TITLE
How did you start learning modern web programming?

### ISSUE THREAD

**Issue by adokh** [kenwheeler/ama#13]
also your advice for new people that want to get into modern web development but find it very overwhelming

**Comment by kenwheeler** [comment]
I kind of got eased into it. I'm old enough to have been doing it a while.

The whole module thing started for me around Dojo time. Then it was requirejs and node modules and bower type stuff. There was Coffeescript and then 6to5 (Babel) came around which was cool. I went through Less then Sass and PostCSS now CSS in JS, etc...

I watched it get more complex in front of my eyes, eagerly trying each new thing as it came along. Even gave talks about how much better it was.

Now, for someone who wants to get into it right now, its gotta be tough. But I'd recommend learning one thing at time, same way I did. 

I learn by building things. So build some things. Each step of the project, or architectural decision, see what the cool kids are using these days (cough: styled-components), and just give it a go. Building things gives you enough challenges to comb over the API surfaces of different libs.
