### ISSUE TITLE
Work / life balance

### ISSUE THREAD

**Issue by knowbody** [kenwheeler/ama#14]
How do you balance your work with your private life? I know that you are a big family man, and also that you spent a lot of time on side project and you also have a full time job, and probably there is more... how do you deal with all that?

What's the typical Ken's week?

**Comment by kenwheeler** [comment]
Lets look at a day:

5/6-8am - Wake up on the couch (My daughter has started sleeping in our bed, and its not big enough for 3, plus I sleep with the TV on). Go to office. Open source, playing with stuff, drinking coffee

8am-9am - I come up, make breakfast, tickle the child, talk with wife about the plans for the day. Breakfast is typically fried eggs and sausage.

9am - noon - Work. Come up for coffee here and there. Sneak in 20 minutes of treadmill intervals

noonish - 1ish - Come up and make lunch. Chicken breasts or something in the winter, Steak or some other thing on the grill if its summer. If its nice outside, go out there for a little.

1 - 4 - More work. 

4 - 5 - Come upstairs to talk dinner and evening plans. Return to wrap up the work day.

5 - 6 or 7 - Make dinner, typically some kind of meat and vegatable setup.

6 or 7 - 9 or 10 - Play with the kid, go to target, watch childrens movies, whiskey (though not lately, green tea instead), bathe the kid, that sort of thing.

10 or 11ish - Wife and child go to bed.

10 or 11ish - 12 or 1ish - Go back downstairs and code some more or talk shit on twitter.

12-1ish - 6am - Sleep restlessly

**Comment by kenwheeler** [comment]
Now keep in mind, this is all shuffleable. I will take hours here and there if theres something cool to do with my daughter or its super nice out. Also I do a 30 minute kickboxing round during 4-5 if I'm not particularly busy (3-5 times a week)

**Comment by alexkvazos** [comment]
Great schedule, i'm just 19 and it already puts a smile on my face reading "playing with the kid" and all of that fun stuff. Congrats man!

**Comment by kenwheeler** [comment]
Kids are fun. There comes a point when you've done a lot of crazy shit and been to every hot restaurant in the area and adulting is getting routine, and its nice to do some fun kid type shit. A whole new group of activities opens up to you. Plus, its amazing being able to introduce a kid to things like cinnamon toast crunch for the first time.
