### ISSUE TITLE
What did you eat for breakfast today, Ken?

### ISSUE THREAD

**Issue by helenvholmes** [kenwheeler/ama#16]
And would you eat it again? Do you eat it often?

That's all kthnx ✌🏽

**Comment by kenwheeler** [comment]
So Im in Amsterdam at the moment. The hotel breakfast buffet is like 18 euros a head, so I was like no way, and walked down the road to a dutch grocery store. 

My wife had asked for conditioner and an american style breakfast sandwich, but the closest thing was this satay chicken filled pastry. Got 2 of those, 2 parfaits and conditioner and this weed cookie, and then walked back. It was lovely. Im still tingling.

I would have it again, but I cant wait for dunkin donuts the second I touch American soil.

**Comment by helenvholmes** [comment]
Dude, breakfast is the thing I miss _most_ when traveling. Ain't nobody who does breakfast like Americans. 

Thanks for answering!
