### ISSUE TITLE
Have you had any nice whiskies recently?

### ISSUE THREAD

**Issue by tjFogarty** [kenwheeler/ama#17]
Also are there any sturdy favourites of yours that you'd recommend?

Sláinte

**Comment by kenwheeler** [comment]
My go to, sippin whiskey, is Makers, Makers 46, and Woodford Reserve for bourbon. Laphroiag 14 for islay.

Had Lagavulin 16 recently again, which is one of my favorites.

Best ever is probably Octomore.
