### ISSUE TITLE
What is the largest animal you're willing to fight armed only with a crossbow?

### ISSUE THREAD

**Issue by tevko** [kenwheeler/ama#18]

**Comment by kenwheeler** [comment]
From what initial distance?

**Comment by tevko** [comment]
Ideally it's an island scenario, wherein you travel (via jetski obvs) to said island to track and kill the beast

**Comment by kenwheeler** [comment]
Largest in size, I'd probably be willing to take on an Indian elephant.

**Comment by kenwheeler** [comment]
By coupling stealth with elevation and distance, I could probably get enough shots off.
