### ISSUE TITLE
what was the last lie you told?

### ISSUE THREAD

**Issue by sintaxi** [kenwheeler/ama#2]

**Comment by kenwheeler** [comment]
Hmm. About 8 hours ago. My wife asked where i got drinks and I said around Dam Square which was true, but I was at a bar in the Red light District. So I suppose more of an untruth than a lie. Last hard lie? I said i hated espresso. I dont hate espresso, I just dont enjoy it as a coffee replacement. Its more of an evening coffee.

**Comment by sintaxi** [comment]
Ah yes, the old Dam Square trick. Thanks for answering. :)
