### ISSUE TITLE
Best place to grab a bite/drink and hang out in New Jersey?

### ISSUE THREAD

**Issue by samelliottdlt** [kenwheeler/ama#20]

**Comment by kenwheeler** [comment]
Well, depends on what you're looking for:

Bro shit: Quaker Steak and Lube in Brick. Beer, football on screen, wings and a punch machine and big buck hunter.

Party: Bar Anticipation in Belmar. Solid place to get housed and do your summer thing. I used to work here and was thrown out on my 21st birthday, while currently employed there.

Fine dining: Restaurant Nicholas in Middletown. Really out of control dishes. Experience type shit.

Hipster shit: Bond St, Bar in Asbury Park. PBR central.

Day drinking: Festhalle in Asbury Park. Ultimate beer garden.

Gentlemans club: Delilahs Den in Toms River. The fun of Centerfolds in Neptune, but a touch easier on the wallet.

Indian food: Moghul in Edison, NJ. Fucking delicious.

Irish Bar: St. Stephens Green in Spring Lake.

Waspy spot: Parker House in Sea Girt. Boat shoe city.

Pizza: Three way tie between Federicos and Dons in Belmar, NJ and Pete and Eldas in Neptune City.
