### ISSUE TITLE
What new tool/framework/tech are you most excited to mess with?

### ISSUE THREAD

**Issue by bbohen** [kenwheeler/ama#21]
I guess this is a two parter really,

- What are you looking forward to messing with for your next piece of OSS awesomeness? 
- Is there a new/upcoming tool that you think will have a major impact on the industry?

Thanks for the AMA and for all the crazy shit you do in general.

**Comment by kenwheeler** [comment]
Well Im pretty excited about ReasonML. I definitely want to do some more with that, and Im pretty sure itll be the next thing.

The next impact on the industry will either make the dom performant, circumvent it, or reduce bundle size and runtime cost by a ton (like svelte)
