### ISSUE TITLE
Web Platform on Desktop vs Web Platform on Mobile Devices

### ISSUE THREAD

**Issue by oojr** [kenwheeler/ama#23]
On twitter I don't think you made a good enough distinction between desktop and mobile when debating between using native apis vs the web platform.

If I was to make a software product with the end goal of making money, I would use React Native for mobile and Electron for anything cross-platform desktop

I believe you like React Native, what would you use for the desktop, Electron or something more native?

**Comment by kenwheeler** [comment]
Well yeah, i meant very specifically for mobile. Electron on desktop is good enough 99% of the time for me. You have access to node so theres a ton more you can do capability wise. Then again, Ive built very few non trivial non electron desktop apps, so theres that.
