### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by clayrisser** [kenwheeler/ama#26]
I'm working on building a react renderer for GTK. I've had a lot of trouble finding documentation on creating custom react renderers. However, I was able to find some direction through some presentations you gave that are on YouTube. I was wondering if you have any good resources you could direct me to for this endeavor. Also, could you put your code for the react emoji project on github. I think it would be helpful for me to look through.

**Comment by kenwheeler** [comment]
I would check this out https://github.com/iamdustan/tiny-react-renderer
and this https://github.com/mhink/react-ionize

Both are super helpful for seeing how it works. The emoji thing is just modifying props on the default dom renderer, but I'll find it and push it up.
