### ISSUE TITLE
Why is 'Murica the greatest country on earth

### ISSUE THREAD

**Issue by mxstbr** [kenwheeler/ama#4]
Apart from Austria, obviously.

**Comment by kenwheeler** [comment]
Its actually even better than Austria. We have a unique set of political, economic and social conditions that make it possible to excel.

**Comment by mxstbr** [comment]
> Its actually even better than Austria

Fight me

![](https://media.giphy.com/media/XtcfqdBrHEa4g/giphy.gif)

**Comment by mxstbr** [comment]
Actually, no please don't

**Comment by kenwheeler** [comment]
Watch your back stoiber
