### ISSUE TITLE
Remote work

### ISSUE THREAD

**Issue by Pinz88** [kenwheeler/ama#9]
What are the biggest pro an cons of working remotely ?
I am a new father who often thinks about the work life benefits of working from home, but fear I would end up just playing with my daughter all day.
Do you have any tips for staying focused or eliminating distractions ?

**Comment by kenwheeler** [comment]
You need a separate room. Also, youll enjoy the break. Trust me. But youll also enjoy being nearby enoug to have lunch every day. Making remote work is 90% communication. Also, cons, get up and walk around. Im all chubby from 300 step count days.
